name: Build and Release WAR

on:
  push:
    tags:
      - '*-v*.*.*'  # Triggers on tags like uat-v1.0.0, cug-v1.0.0, prod-v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build WAR with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-war
          path: target/*.war

  extract-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setenv.outputs.env }}
    steps:
      - name: Set environment name
        id: setenv
        run: |
          TAG_NAME="${{ github.ref_name }}"
          ENVIRONMENT=$(echo "$TAG_NAME" | cut -d'-' -f1 | tr '[:lower:]' '[:upper:]')
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "env=$ENVIRONMENT" >> "$GITHUB_OUTPUT"

  release:
    needs: [build, extract-env]
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR from build job
        uses: actions/download-artifact@v4
        with:
          name: java-war

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: '*.war'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create Jira Ticket and Upload WAR
        env:
          JIRA_EMAIL: ${{ vars.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT: ${{ vars.JIRA_PROJECT }}
          ASSIGNEE_ID: ${{ vars.ASSIGNEE_ID }}
          TAG_NAME: ${{ github.ref_name }}
          ENVIRONMENT_NAME: ${{ needs.extract-env.outputs.environment }}
        run: |
          echo "Detected Environment: $ENVIRONMENT_NAME"
          WAR_FILE=$(find . -name "*.war" | head -n 1)

          echo "Creating Jira payload..."
          cat <<EOF > payload.json
          {
            "fields": {
              "project": { "key": "${JIRA_PROJECT}" },
              "summary": "WAR build and release successful - ${TAG_NAME}",
              "description": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": "Automated build and GitHub release completed for tag ${TAG_NAME} in ${ENVIRONMENT_NAME} environment."
                      }
                    ]
                  }
                ]
              },
              "issuetype": { "name": "Task" },
              "assignee": { "name": "${ASSIGNEE_ID}" }
            }
          }

          EOF
          echo "Payload content:"
          cat payload.json

          ISSUE_RESPONSE=$(curl -s -X POST \
            --url "https://jira.icicibank.com/rest/api/latest/issue" \
            --user "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
            --header "Content-Type: application/json" \
            --data @payload.json)


          echo "Raw ISSUE_RESPONSE: $ISSUE_RESPONSE"
          ISSUE_KEY=$(echo "$ISSUE_RESPONSE" | jq -r '.key')

          if [ "$ISSUE_KEY" == "null" ] || [ -z "$ISSUE_KEY" ]; then
            echo "❌ Failed to create Jira issue. Response: $ISSUE_RESPONSE"
            exit 1
          fi

          echo "✅ Created Jira issue: $ISSUE_KEY"

          curl -s -X POST \
            --url "https://jira.icicibank.com/rest/api/latest/issue/${ISSUE_KEY}/attachments" \
            --user "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
            --header "X-Atlassian-Token: no-check" \
            --header "Content-Type: multipart/form-data" \
            --form "file=@${WAR_FILE}"

          curl -s -X POST \
            --url "https://jira.icicibank.com/rest/api/latest/issue/${ISSUE_KEY}/comment" \
            --user "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
            --header "Content-Type: application/json" \
            --data "{
              \"body\": \"WAR file uploaded successfully for tag ${TAG_NAME}.\"
            }"
